import { describe, it, expect } from 'vitest';
import { generateDDL } from '../../src/services/ddl-generator.service.js';
import type { PgTableMetadata, PgColumn } from '../../src/types/postgres.js';

function makeColumn(overrides: Partial<PgColumn> = {}): PgColumn {
  return {
    schemaName: 'public',
    tableName: 'users',
    columnName: 'id',
    ordinalPosition: 1,
    columnDefault: null,
    isNullable: false,
    dataType: 'integer',
    udtName: 'int4',
    characterMaximumLength: null,
    numericPrecision: null,
    numericScale: null,
    isIdentity: true,
    identityGeneration: 'ALWAYS',
    ...overrides,
  };
}

function makeTable(overrides: Partial<PgTableMetadata> = {}): PgTableMetadata {
  return {
    schemaName: 'public',
    tableName: 'users',
    columns: [
      makeColumn({ columnName: 'id', isIdentity: true, isNullable: false }),
      makeColumn({ columnName: 'name', udtName: 'varchar', dataType: 'character varying', characterMaximumLength: 100, isNullable: false, isIdentity: false }),
      makeColumn({ columnName: 'email', udtName: 'varchar', dataType: 'character varying', characterMaximumLength: 255, isNullable: true, isIdentity: false }),
      makeColumn({ columnName: 'created_at', udtName: 'timestamptz', dataType: 'timestamp with time zone', isNullable: false, isIdentity: false, columnDefault: 'now()' }),
    ],
    primaryKey: {
      schemaName: 'public',
      tableName: 'users',
      constraintName: 'users_pkey',
      columns: ['id'],
    },
    foreignKeys: [],
    indexes: [],
    sequences: [],
    ...overrides,
  };
}

describe('ddl-generator.service', () => {
  it('should generate header with timestamp and constraint note', async () => {
    const result = await generateDDL([makeTable()]);
    expect(result.sql).toContain('Snowflake DDL generated by pgtosnowflake');
    expect(result.sql).toContain('NOT enforced');
  });

  it('should generate CREATE SCHEMA statements', async () => {
    const result = await generateDDL([makeTable()]);
    expect(result.sql).toContain('CREATE SCHEMA IF NOT EXISTS "public";');
    expect(result.schemaCount).toBe(1);
  });

  it('should generate CREATE TABLE with columns', async () => {
    const result = await generateDDL([makeTable()]);
    expect(result.sql).toContain('CREATE TABLE IF NOT EXISTS "public"."users"');
    expect(result.sql).toContain('"id" INTEGER IDENTITY(1,1) NOT NULL');
    expect(result.sql).toContain('"name" VARCHAR(100) NOT NULL');
    expect(result.sql).toContain('"email" VARCHAR(255)');
    expect(result.tableCount).toBe(1);
  });

  it('should include PRIMARY KEY inline', async () => {
    const result = await generateDDL([makeTable()]);
    expect(result.sql).toContain('PRIMARY KEY ("id")');
  });

  it('should include DEFAULT for timestamp columns', async () => {
    const result = await generateDDL([makeTable()]);
    expect(result.sql).toContain('DEFAULT CURRENT_TIMESTAMP()');
  });

  it('should generate foreign keys as ALTER TABLE statements', async () => {
    const orders = makeTable({
      tableName: 'orders',
      columns: [
        makeColumn({ tableName: 'orders', columnName: 'id', isIdentity: true, isNullable: false }),
        makeColumn({ tableName: 'orders', columnName: 'user_id', udtName: 'int4', isNullable: false, isIdentity: false }),
      ],
      primaryKey: {
        schemaName: 'public',
        tableName: 'orders',
        constraintName: 'orders_pkey',
        columns: ['id'],
      },
      foreignKeys: [{
        schemaName: 'public',
        tableName: 'orders',
        constraintName: 'orders_user_id_fkey',
        columns: ['user_id'],
        referencedSchema: 'public',
        referencedTable: 'users',
        referencedColumns: ['id'],
        updateRule: 'NO ACTION',
        deleteRule: 'CASCADE',
      }],
    });

    const result = await generateDDL([makeTable(), orders]);
    expect(result.sql).toContain('ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_user_id_fkey"');
    expect(result.sql).toContain('FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id")');
    expect(result.foreignKeyCount).toBe(1);
  });

  it('should handle multiple schemas', async () => {
    const table1 = makeTable({ schemaName: 'public' });
    const table2 = makeTable({ schemaName: 'analytics', tableName: 'events' });

    const result = await generateDDL([table1, table2]);
    expect(result.sql).toContain('CREATE SCHEMA IF NOT EXISTS "analytics";');
    expect(result.sql).toContain('CREATE SCHEMA IF NOT EXISTS "public";');
    expect(result.schemaCount).toBe(2);
    expect(result.tableCount).toBe(2);
  });

  it('should quote all identifiers', async () => {
    const table = makeTable({
      schemaName: 'My Schema',
      tableName: 'My Table',
      columns: [
        makeColumn({ schemaName: 'My Schema', tableName: 'My Table', columnName: 'My Column', isIdentity: false }),
      ],
      primaryKey: null,
    });

    const result = await generateDDL([table]);
    expect(result.sql).toContain('"My Schema"');
    expect(result.sql).toContain('"My Table"');
    expect(result.sql).toContain('"My Column"');
  });

  it('should add comments for user-defined types', async () => {
    const table = makeTable({
      columns: [
        makeColumn({ columnName: 'status', udtName: 'status_enum', dataType: 'USER-DEFINED', isIdentity: false }),
      ],
      primaryKey: null,
    });

    const result = await generateDDL([table]);
    expect(result.sql).toContain('COMMENT ON COLUMN');
    expect(result.sql).toContain('user-defined type: status_enum');
  });
});
